version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/react/build
    stdin_open: true

  backend:
    build:
      context: .
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - react_build:/var/www/react
    depends_on:
      - frontend
      - backend


volumes:
  react_build:


