version: "3.8"

services:
  backend:
    build:
      context: .
    volumes:
      - .:/app2
      - static_volume:/app2/staticfiles
      - media_volume:/app2/mediafiles   
    expose:
      - 8000

  nginx:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - static_volume:/app2/staticfiles
      - media_volume:/app2/mediafiles    
    depends_on:
      - backend


volumes:
  static_volume:
  media_volume:


